spring:
  flyway:
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.shyrski.profit.tracker.config.hibernate.UpperCaseNamingStrategy
  datasource:
    url: ${MARIADB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 5

security:
  oauth2:
    resource:
      userInfoUri: https://profit-tracker-service.auth.eu-north-1.amazoncognito.com/oauth2/userInfo
      tokenInfoUri: https://profit-tracker-service.auth.eu-north-1.amazoncognito.com/oauth2/token
      jwk:
        key-set-uri: ${COGNITO_KEY_SET_URL}
    client:
      clientId: ${COGNITO_CLIENT_ID}