spring:
  flyway:
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.shyrski.profit.tracker.config.hibernate.UpperCaseNamingStrategy
  datasource:
    url: jdbc:mariadb://localhost:3306/profit-tracker-service
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 3

springdoc:
  packages-to-scan: com.shyrski.profit.tracker.controller
  paths-to-match: /api/v1/**

aws:
  region: eu-north-1
  key-id: ${AWS_KEY_ID}
  key-secret: ${AWS_KEY_SECRET}
  s3:
    collection-image-bucket-name: profit-tracker-bucket-dev/collection-images
    nft-image-bucket-name: profit-tracker-bucket-dev/nfts

security:
  oauth2:
    resource:
      userInfoUri: https://profit-tracker-service.auth.eu-north-1.amazoncognito.com/oauth2/userInfo
      tokenInfoUri: https://profit-tracker-service.auth.eu-north-1.amazoncognito.com/oauth2/token
      jwk:
        key-set-uri: ${COGNITO_KEY_SET_URL}
    client:
      clientId: ${COGNITO_CLIENT_ID}

opensea:
  base-url: https://api.opensea.io/api/v1
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${MARIADB_URL}
    username: profit-tracker-service
    password: ${MARIADB_PASSWORD}
    hikari:
      maximum-pool-size: 5