CREATE SEQUENCE collections_sequence
    START WITH 3457
    MINVALUE 0
    INCREMENT BY 50;

CREATE SEQUENCE portfolio_sequence
    START WITH 7030
    MINVALUE 0
    INCREMENT BY 50;

CREATE SEQUENCE nft_sequence
    START WITH 1982
    MINVALUE 0
    INCREMENT BY 50;