CREATE TABLE IF NOT EXISTS COLLECTION_MARKETPLACE
(
    COLLECTION_MARKETPLACE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME                      VARCHAR(50)     NOT NULL UNIQUE,
    CREATION_DATE             DATETIME        NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    CREATED_BY                VARCHAR(45)     NULL,
    LAST_UPDATE_DATE          DATETIME        NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    LAST_UPDATED_BY           VARCHAR(45)     NULL,
    PRIMARY KEY (`COLLECTION_MARKETPLACE_ID`)
)
    ENGINE = InnoDB;

ALTER TABLE COLLECTION
    ADD COLUMN TYPE              VARCHAR(50)     NOT NULL AFTER IMAGE_KEY,
    ADD COLUMN ID_IN_MARKETPLACE VARCHAR(200)    NULL AFTER TYPE,
    ADD COLUMN MARKETPLACE_ID    BIGINT UNSIGNED NULL AFTER ID_IN_MARKETPLACE,
    ADD COLUMN URL               VARCHAR(200)    NULL AFTER ID_IN_MARKETPLACE,
    MODIFY NETWORK_ID BIGINT UNSIGNED NULL,
    MODIFY IMAGE_KEY VARCHAR(300) NULL AFTER NAME;

ALTER TABLE COLLECTION
    ADD CONSTRAINT fk_COLLECTION_MARKETPLACE_ID
        FOREIGN KEY (MARKETPLACE_ID) REFERENCES COLLECTION_MARKETPLACE (COLLECTION_MARKETPLACE_ID);

ALTER TABLE NETWORK
    MODIFY NAME VARCHAR(50) NOT NULL UNIQUE;

CREATE SEQUENCE COLLECTIONS_SEQUENCE
    START WITH 3457
    MINVALUE 0
    INCREMENT BY 50;

CREATE SEQUENCE PORTFOLIO_SEQUENCE
    START WITH 7030
    MINVALUE 0
    INCREMENT BY 50;

CREATE SEQUENCE NFT_SEQUENCE
    START WITH 1982
    MINVALUE 0
    INCREMENT BY 50;

ALTER TABLE NFT
    ADD COLUMN TOKEN_ID          VARCHAR(50)  NULL AFTER COLLECTION_ID,
    ADD COLUMN DESCRIPTION       LONGTEXT     NULL AFTER TOKEN_ID,
    ADD COLUMN ID_IN_MARKETPLACE VARCHAR(50)  NULL AFTER DESCRIPTION,
    ADD COLUMN CONTRACT_ADDRESS  VARCHAR(100) NULL AFTER ID_IN_MARKETPLACE,
    ADD COLUMN TYPE              VARCHAR(50)  NOT NULL AFTER IMAGE_KEY,
    MODIFY IMAGE_KEY VARCHAR(300) NULL AFTER NAME;
