CREATE TABLE IF NOT EXISTS NETWORK
(
    NETWORK_ID       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME             VARCHAR(50)     NOT NULL,
    CREATION_DATE    DATETIME        NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    CREATED_BY       VARCHAR(45)     NULL,
    LAST_UPDATE_DATE DATETIME        NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    LAST_UPDATED_BY  VARCHAR(45)     NULL,
    PRIMARY KEY (`NETWORK_ID`)
)
    ENGINE = InnoDB;

ALTER TABLE COLLECTION
    ADD COLUMN NETWORK_ID BIGINT UNSIGNED NOT NULL AFTER IMAGE_KEY;

ALTER TABLE COLLECTION
    ADD CONSTRAINT fk_NETWORK_COLLECTION
        FOREIGN KEY (NETWORK_ID) REFERENCES NETWORK (NETWORK_ID);
